# Importar los programas necesarios
import programa_variables
import programa_tipos
import programa_area_triangulo
import programa_perimetro_rectangulo
import programa_area_trapecio
import programa_volumen_prisma
import programa_ecuaciones
import programa_resolucion_ecuaciones
import programa_conversion_unidades
import programa_regla_de_tres
import programa_calculo_interes_prestamo
import programa_calculo_salario_neto
import programa_calculo_costo_gasolina
import programa_calculo_costo_articulos
import programa_calculo_nota_final
import programa_calculo_compra_articulos
import programa_determinar_impuestos
import programa_clasificar_triangulos
import programa_clasificar_numeros
import programa_clasificar_calificaciones
import programa_mostrar_numeros
import programa_calculo_area_triangulo
import programa_verificar_primo
import programa_serie_fibonacci
import programa_calculo_factorial
import programa_tabla_multiplicar
import programa_imprimir_numeros
import programa_calculo_impuesto
import programa_suma_pares

# Ejecutar los programas
programa_variables.programa_variables()
programa_tipos.programa_tipos()
programa_area_triangulo.programa_area_triangulo()
programa_perimetro_rectangulo.programa_perimetro_rectangulo()
programa_area_trapecio.programa_area_trapecio()
programa_volumen_prisma.programa_volumen_prisma()
programa_ecuaciones.programa_ecuaciones()
programa_resolucion_ecuaciones.programa_resolucion_ecuaciones()
programa_conversion_unidades.programa_conversion_unidades()
programa_regla_de_tres.programa_regla_de_tres()
programa_calculo_interes_prestamo.programa_calculo_interes_prestamo()
programa_calculo_salario_neto.programa_calculo_salario_neto()
programa_calculo_costo_gasolina.programa_calculo_costo_gasolina()
programa_calculo_costo_articulos.programa_calculo_costo_articulos()
programa_calculo_nota_final.programa_calculo_nota_final()
programa_calculo_compra_articulos.programa_calculo_compra_articulos()
programa_determinar_impuestos.programa_determinar_impuestos()
programa_clasificar_triangulos.programa_clasificar_triangulos()
programa_clasificar_numeros.programa_clasificar_numeros()
programa_clasificar_calificaciones.programa_clasificar_calificaciones()
programa_mostrar_numeros.programa_mostrar_numeros()
programa_calculo_area_triangulo.programa_calculo_area_triangulo()
programa_verificar_primo.programa_verificar_primo()
programa_serie_fibonacci.programa_serie_fibonacci()
programa_calculo_factorial.programa_calculo_factorial()
programa_tabla_multiplicar.tabla_multiplicar()
programa_imprimir_numeros.imprimir_numeros()
programa_calculo_impuesto.calcular_impuesto()
programa_suma_pares.sumar_numeros_pares(20)
programa_calculo_area_triangulo.calcular_area_triangulo(5, 8)
